### ISSUE TITLE
Issues rendering/loading pages

### ISSUE THREAD

**Issue by Dreamwxve** [IgorKowalczyk/majo.exe#1046]
### Environment

Windows 11 Home 23H2 Build 22631.3880

### Steps To Reproduce

N/A

### Software Version

latest from repo

### Expected Behavior

`useContext(VisibilityContext)` to not return null

### Actual Behavior

`useContext(VisibilityContext)` returns null and causes everything else to just fall apart

### Screenshots

N/A

### Severity

Critical

### Priority

High

### Type

Functional, Usability

### Additional Information

So after a day and a night of debugging I isolated the issue and within the navbar components, the line(s) 
```jsx
const { sideNavVisible, toggleSideNav } = useContext(VisibilityContext);
```
return a value of null. JSX is not my strongsuit but ill see what I can do to fix this. Everything seems to be used properly, the visibilityprovider is correctly wrapping everything that uses it and it does export itself as readable context. So I have no idea for now

**Comment by IgorKowalczyk** [comment]
`VisibilityContext` is only used on `/dashboard` pages, I don't know what it would have to do with endpoints `/api/*`.

VisibilityContext will be null when used outside of its provider, but from the configuration it looks like everything is set up as it should be. Can you give the console logs? It will help me to look for the problem because I can't reproduce this error.

**Comment by IgorKowalczyk** [comment]
Check that these values in the .env file are set like this:

```
NEXTAUTH_URL=http://localhost:3000
NEXT_PUBLIC_URL=http://localhost:3000
```

**Comment by IgorKowalczyk** [comment]
Hmm, so everything looks fine to me, I will check the code on my Windows 11 VM later.

We can keep chatting here so other people can solve a similar problem later.

And just so you know - Majo.exe was never designed to run on Windows, thanks to your help, maybe it will be possible to improve it enough to run on Windows without any problems.

**Comment by IgorKowalczyk** [comment]
Recently I had such a problem in another project, it was not related to hooks but to incorrectly used components

**Comment by IgorKowalczyk** [comment]
> Found the issue:
> ```html
>     <head>
>         {process.env.HOTJAR_ID && <Hotjar id={process.env.HOTJAR_ID} />}
>     </head>
> 
> ```
> Commenting that line out fixed absolutely everything. `process.env.HOTJAR_ID` does infact return my hotjar ID and i removed it from `.env` and the site still failed to work. Must be how the hotjar component is formatted and returned. Rest of my problems now lie with the prisma schema and how the rest of the code interacts with the database, not too much of a hassle.
> 

I think it's not hotjar at all because removing this one line should fully solve the problem, hotjar is just a website monitoring tool and is not used anywhere else in the codebase

**Comment by TsukiyoDevs** [comment]
Removing the hotjar from the head makes the site load and compile properly, the issue with the:
```js
TypeError: Cannot read properties of null (reading 'useContext')
```
still exist and I have no idea how to address the issue as i console logged every reference of use Context and it did not return null, nor was the param passed to it everytime.

`next dev` runs the site fine everything loads and works (minus the prisma stuff on my end), removing the globe removes the lag the main page. `next build` is where all these errors start.

another odd issue i started to notice was i left the terminal running `next dev` for a while and redis started throwing errors of "maximum number of clients reached", what could that be about? Also the "Discord Profile" button on the profile page the link doesnt exist anymore, well discord doesn't use it anymore.

off topic question, with the suggestions its data just gets sent to the database. Is this an unfinished command? Could possibly have a page on the dropdown at the top right corner for developers to view these suggestions and accept/deny and with an optional reason that gets dmed to the user, that would be cool.

**Comment by IgorKowalczyk** [comment]
Hmm, really weird, I will check it later

**Comment by IgorKowalczyk** [comment]
And yes - the suggestion command is unfinished. I'm working on integrating it into the dashboard

**Comment by TsukiyoDevs** [comment]
Sweet sweet! Well been at this and really unable to find why next build doesnt work. Errors that use context is being passed/returns a null value when console logging so I have no idea on that part of it. Unless you use another command for building that isnt next build? (Also assuming that if i cant build the project on the terminal, it wont work on vercel either)

**Comment by Dreamwxve** [comment]
I think its safe to say everything now works properly on windows!
