### ISSUE TITLE
mysql database result in a error.

### ISSUE THREAD

**Issue by Salvi0** [IgorKowalczyk/majo.exe#32]
I'm trying to host the bot on railway.app wich offer a free mysql database. But this error constatly pop-up
![image](https://user-images.githubusercontent.com/66015217/146840120-21ea65bb-571d-43d0-a2c9-51828f85cf10.png)

**Comment by Salvi0** [comment]
in addition to this, i tried to change the port and this was the result
![image](https://user-images.githubusercontent.com/66015217/146840767-51db8def-b96c-4878-b32f-569d315fc1a1.png)

**Comment by IgorKowalczyk** [comment]
Please check if you can connect to the database e.g. via phpmyadmin. You may not be whitelist to connect.

**Comment by MashedTuna** [comment]
how do i connet to the database using phpmyadmin?

**Comment by IgorKowalczyk** [comment]
> how do i connet to the database using phpmyadmin?

You need to have database address, database name, user and password, that's all

**Comment by MashedTuna** [comment]
> > how do i connet to the database using phpmyadmin?
> 
> You need to have database address, database name, user and password, that's all
i alr did,but then i get this error 
![image](https://user-images.githubusercontent.com/78328022/149604520-c01644fe-6073-45c4-9236-7e3178db8abd.png)

**Comment by IgorKowalczyk** [comment]
You can run these scripts manually: https://github.com/IgorKowalczyk/majobot/blob/master/utilities/database-scripts.js#L4
