### ISSUE TITLE
prefix not working

### ISSUE THREAD

**Issue by TheGamer3514** [IgorKowalczyk/majo.exe#34]
in config i set prefix as ; but it does not work, please help

**Comment by MashedTuna** [comment]
change your .replit run script to npm run-script start

**Comment by IgorKowalczyk** [comment]
The bot appeared online (displays status etc) but does not respond to messages or the bot just appeared online (without status change etc)?
Also check the slash commands to see if they work

**Comment by TheGamer3514** [comment]
only appears online

**Comment by TheGamer3514** [comment]
> change your .replit run script to npm run-script start

![image](https://user-images.githubusercontent.com/79448904/149619393-cdac8b6b-bbc6-4a74-8571-55a732c8ccf9.png)
get this error now and only website runs

**Comment by MashedTuna** [comment]
> > change your .replit run script to npm run-script start
> 
> ![image](https://user-images.githubusercontent.com/79448904/149619393-cdac8b6b-bbc6-4a74-8571-55a732c8ccf9.png) get this error now and only website runs

hmm i have the same error but it won't crash+it connected to the sql db and the bot working properly
