### ISSUE TITLE
Mysql version issue

### ISSUE THREAD

**Issue by JanjyTapYT** [IgorKowalczyk/majo.exe#41]
Hello i get this error when i try to start all with the replit npm start command:
![Firefox_Screenshot_2022-02-02T18-50-27 365Z](https://user-images.githubusercontent.com/81481526/152218754-af06acc8-fb1a-445c-b645-618ff6d70f91.png)

PLS help
Note: 1 time i tryed it said i need to install node v16+ but node v16+ is installed
@IgorKowalczyk

**Comment by IgorKowalczyk** [comment]
Your MySQL version must be higher than 5.7 to run Majo.exe

**Comment by JanjyTapYT** [comment]
How can I change this?

**Comment by IgorKowalczyk** [comment]
Simply install a new version of MYSQL on the server. If you use free MySQL hosting you need to find another one, most of them don't offer newer versions

**Comment by JanjyTapYT** [comment]
can someone send me an link to an free MySQL host who supports 5.7?

**Comment by Inopiu** [comment]
can someone send me an link to an free MySQL host who supports 5.7?

**Comment by JanjyTapYT** [comment]
WOW

**Comment by IgorKowalczyk** [comment]
You can try this: https://remotemysql.com
