### ISSUE TITLE
How to run Dashboard, API and Bot at the same time?

### ISSUE THREAD

**Issue by NeedSomeSoftware** [IgorKowalczyk/majo.exe#46]
How to run Dashboard, API and Bot at the same time?

npm run majo:bot <- Bot Run
npm run majo:dashboard <- Dashboard Run
npm run majo:api <- API Run
while true; do npm run majo:web; sleep 2; done <- Dashboard and API Run 

But I don't know how to run all three in the same command (If I just add --bot it crashes)

**Comment by IgorKowalczyk** [comment]
Please run `npm run start`
