### ISSUE TITLE
help my app forgot its username 

### ISSUE THREAD

**Issue by masterofninja** [IgorKowalczyk/majo.exe#48]
/app/utilities/client/anti-crash.js:42
   username: `${client.user.username} Error`,
                            ^

TypeError: Cannot read properties of null (reading 'username')
    at process.<anonymous> (/app/utilities/client/anti-crash.js:42:29)
    at process.emit (node:events:526:28)
    at process._fatalException (node:internal/process/execution:164:13)

**Comment by IgorKowalczyk** [comment]
Does the console display information that the bot successfully logged into Discord?

**Comment by masterofninja** [comment]
yes it shows the green checkmarks when the MySQL successfully connected

**Comment by masterofninja** [comment]
so I moved from Heroku to reptil and still same code

**Comment by IgorKowalczyk** [comment]
Fixed in https://github.com/IgorKowalczyk/majo.exe/commit/4d848e30be4657ba2fa68b2b791b2911da74ac9f
