### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'endsWith')

### ISSUE THREAD

**Issue by Aceeeeeeeeeee** [IgorKowalczyk/majo.exe#51]
**Hello, I tried to use your repository as an attempt to modify it just for fun, But, When I tried to run it, I ran into some errors.**

```
TypeError: Cannot read properties of undefined (reading 'endsWith')
at Object.<anonymous> (/home/runner/majoexe/web/web.js:5:35)
```

**and another error in the same process**

```
/home/runner/majoexe/node_modules/mysql/lib/protocol/Parser.js:437
     throw err; // Rethrow non-MySQL errors`
             ^
Error: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON NULL, `leaves` JSON NULL, `last_updated` DATE NOT NULL, PRIMARY KEY (`guild' at line 1
    at Query.<anonymous> (/home/runner/majoexe/utilities/mysql/database.js:37:22)
   at Query.<anonymous> (/home/runner/majoexe/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/runner/majoexe/node_modules/mysql/lib/Connection.js:488:16)
   at Query.Sequence.end (/home/runner/majoexe/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
```

**Comment by IgorKowalczyk** [comment]
1. `process.env.DOMAIN` is undefined. it is possible that there is no `.env` file
2. [Your MySQL version is too old](https://github.com/IgorKowalczyk/majo.exe#%EF%B8%8F-requirements)

**Comment by Aceeeeeeeeeee** [comment]
By the way, is there anyway possible to get a free MySQL database, since I really can't find anything good as described.

**Comment by IgorKowalczyk** [comment]
Unfortunately I don't know any free mysql host. However, if you want MySQL (+ Bot hosting) at a very low price you can use [https://terohost.com](https://my.terohost.com/index.php?rp=/store/discord-bot-hosting)
