### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by aziz191546** [IgorKowalczyk/majo.exe#53]
add rank commands and security commands like anti-nuke and welcome-leave dm and wlcavatar , add info commands ...
you can inspiration Commands from this https://github.com/Tomato6966/Multipurpose-discord-bot

**Comment by IgorKowalczyk** [comment]
I plan to do all this but currently don't have time. On April 30th I plan to release a new version of majo, but I have a feeling that it will be incomplete

**Comment by aziz191546** [comment]
just try to add Necessary Commands like rection role welcome -leave dm advanced Logger ...
