### ISSUE TITLE
MYSQL Error (ER_NOT_SUPPORTED_AUTH_MODE)

### ISSUE THREAD

**Issue by marc16w** [IgorKowalczyk/majo.exe#59]
i have this error on the bot: Database error: ER_NOT_SUPPORTED_AUTH_MODE

**Comment by IgorKowalczyk** [comment]
Can you provide some additional information about this error? Version of mysql, server on which mysql is running, etc.

**Comment by marc16w** [comment]
Last version of mysql and runing in buntu 20.04 server

**Comment by IgorKowalczyk** [comment]
I can't help much, it is an error on your side. You can reinstall mysql server, check passwords, etc.
