### ISSUE TITLE
PostgreSQL to mongodb

### ISSUE THREAD

**Issue by FreakyMorex** [IgorKowalczyk/majo.exe#710]
### What is the improvement or update you wish to see?

I want to use mongodb

### Is there any context that might help us understand?

I want to use mongodb

**Comment by IgorKowalczyk** [comment]
Docs: https://www.prisma.io/docs/orm/overview/databases/mongodb#more-on-using-mongodb-with-prisma

**Comment by FreakyMorex** [comment]
> Majo does not support mongodb in the default configuration, mongodb can work after modifying the file and most likely modifying the code.`schema.prisma`
> 
> Docs: https://www.prisma.io/docs/orm/overview/databases/mongodb#more-on-using-mongodb-with-prisma

Can't you try ?

**Comment by IgorKowalczyk** [comment]
No, Majo.exe primarily supports only PostgreSQL and MySQL, you can add mongodb support yourself

**Comment by FreakyMorex** [comment]
> No, Majo.exe primarily supports only PostgreSQL and MySQL, you can add mongodb support yourself

Okey, Thank You
